---
title             : "Indigenous High-school Completion"
shorttitle        : "A Quantitative Intersectional Perspective"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Professor Phil Parker is the Deputy Director of the Institute for Positive Psychology and Education at the Australian Catholic University. He received his doctorate in Educational Psychology from the University of Sydney. His major research interest includes educational inequality, developmental transitions, and educational attainment.

abstract: |
  Abstract will go here
  
  
keywords          : "keywords"
wordcount         : "X"

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
library(foreign)
library(haven)
library(Hmisc)
library(psych)
library(apaTables)
library(tidyverse)
library(ggtext)
library(ggeffects)
library(magrittr)
library(broom)
library(stringr)
library(foreign)
library(srvyr)
library(svyPVpack)
library(survey)
library(lme4)
library(patchwork)
library(ggthemes)
library(ggtext)
```

```{r analysis-preferences, include = FALSE, message=FALSE, warning=FALSE, error=FALSE}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
lsay2009<- readit::readit("~/cloudstor/Databases/2020-03-12_LSAY/LSAY_2009.dta")
lsay2003<- readit::readit("~/cloudstor/Databases/LSAY_DATSETS/LSAY2003_2016.sav")
# 2003 
lsay2003short <- lsay2003 %>%
  setNames(toupper(names(.)))%>%
  filter(!is.na(WT2004) ) %>% #Not sure wether to use 2004 weights or 2007
  select(WT2 = WT2007, starts_with("PV"), INDIG, GENDER = SEX, GEO = LOC,
         SCH10 = LBWDV01, SCH11 = LCWDV01, SCH12 = LDWDV01, SCH13 = LEWDV01,
         STATEID, GRADE = ST01Q01,
         SC = LAA027, WT = WT2004, ESCS, starts_with("W_FSTR")) %>%
  mutate(ESCS = replace(ESCS, ESCS > 900, NA),
         INDIG = replace(INDIG, INDIG == 8,NA),
         GRADE = replace(GRADE, GRADE > 90, NA),
         GENDER = case_when(
           GENDER == 1 ~ 1, #1 is male
           GENDER == 2 ~ 0  #0 is female
         ),
         DROPOUT = case_when(
           SCH10 == 1 ~ 1,
           SCH11 == 1 ~ 1,
           SCH12 == 1 ~ 1,
           SCH13 == 1 ~ 1,
           SCH10 != 1 ~ 0,
           SCH11 != 1 ~ 0,
           SCH12 != 1 ~ 0,
           SCH13 != 1 ~ 0,
           TRUE ~ NA_real_
         ),
         GEO = case_when(
           GEO == 1 ~ 1,
           TRUE ~ 0
         ),
         ACH1PV = principal(.[,c("PV1READ","PV1SCIE","PV1MATH")],nfactors = 1)$scores,
         ACH2PV = principal(.[,c("PV2READ","PV2SCIE","PV2MATH")],nfactors = 1)$scores,
         ACH3PV = principal(.[,c("PV3READ","PV3SCIE","PV3MATH")],nfactors = 1)$scores,
         ACH4PV = principal(.[,c("PV4READ","PV4SCIE","PV4MATH")],nfactors = 1)$scores,
         ACH5PV = principal(.[,c("PV5READ","PV5SCIE","PV5MATH")],nfactors = 1)$scores
  ) %>%
  as_survey_rep(type = "Fay", rho = .05, repweights = starts_with("W_FSTR"), weights = WT)

# LSAY 2009
lsay2009short <-lsay2009 %>% 
  filter(!is.na(WT2010)) %>% #Not sure wether to use 2010 weights or 2013
  select(WT2 = WT2013,starts_with("PV"), INDIG, GENDER = ST04Q01, 
         SCH10 = LBWDV01, SCH11 = LCWDV01, SCH12 = LDWDV01, SCH13 = LEWDV01,
         STATEID = STATE, GRADE = ST01Q01, GEO = GEOLOC,
         SC = ST62N04, WT = WT2010, ESCS, starts_with("W_FSTR")) %>%
  select(-matches("READ[1-9]+")) %>%
  mutate(ESCS = replace(ESCS, ESCS > 900, NA),
         INDIG = replace(INDIG, INDIG == 8,NA),
         GRADE = replace(GRADE, GRADE > 90, NA),
         #hisced = replace(HISCED, HISCED > 8, NA),
         GENDER = case_when(
           GENDER == 2 ~ 1, #1 is male
           GENDER == 1 ~ 0, #0 is female
           TRUE ~ NA_real_
         ),
         DROPOUT = case_when(
           SCH10 == 1 ~ 1,
           SCH11 == 1 ~ 1,
           SCH12 == 1 ~ 1,
           SCH13 == 1 ~ 1,
           SCH10 != 1 ~ 0,
           SCH11 != 1 ~ 0,
           SCH12 != 1 ~ 0,
           SCH13 != 1 ~ 0,
           TRUE ~ NA_real_
         ),
         GEO = case_when(
           GEO == 1 ~ 1, # 1 is Urban
           TRUE ~ 0 # 0 is Rural
         ),
         ACH1PV = principal(.[,c("PV1READ","PV1SCIE","PV1MATH")],nfactors = 1)$scores,
         ACH2PV = principal(.[,c("PV2READ","PV2SCIE","PV2MATH")],nfactors = 1)$scores,
         ACH3PV = principal(.[,c("PV3READ","PV3SCIE","PV3MATH")],nfactors = 1)$scores,
         ACH4PV = principal(.[,c("PV4READ","PV4SCIE","PV4MATH")],nfactors = 1)$scores,
         ACH5PV = principal(.[,c("PV5READ","PV5SCIE","PV5MATH")],nfactors = 1)$scores
  ) %>%
  as_survey_rep(type = "Fay", rho = .05, repweights = starts_with("W_FSTR"), weights = WT)

z <- function(z) {(z-mean(z, na.rm=TRUE))/sd(z, na.rm=TRUE)}
# Combine the cohorts
# #Warnings relate to survey not liking labelled data. These can be safely ignored
lsay <- bind_rows(lsay2003short$variables, lsay2009short$variables,.id = "COHORT") %>%
  mutate(STATEID = factor(STATEID),
         SC = z(SC)*-1,
         STATE2 = case_when(
           STATEID %in% 1:3 ~ 1,
           TRUE ~ 0
         ),
         FLAG_MISS = ifelse(is.na(WT2), 1,0),
         DROPOUT_10 = ifelse(SCH10 == 1, 1,0)
         )

# Using old school survey package here in order for ggeffects to work
lsay <- svrepdesign(data=lsay, weights=~WT, repweights = "W_FSTR[1-9]+", type="Fay", rho = .5, )
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
```{r results='asis', message=FALSE, warning=FALSE, error=FALSE}
H1 <- svyglm(DROPOUT ~ INDIG+COHORT+GRADE+STATE2+GEO+GENDER+FLAG_MISS+ESCS,design = lsay,family = quasibinomial())

H1_tidy <- tidy(H1,conf.int=TRUE)

H1_tidy %>%
  select(-std.error,-statistic) %>%
  select(term, estimate, conf.low, conf.high,p.value)%>%
  papaja::printnum() %>%
  mutate(p.value = ifelse(p.value == "0.00",  "< .001", p.value),
         term = replace(term, term =="(Intercept)", "Intercept")) %>%
  setNames(c("Predictor", "Log Odds", "-95%", "+95%", "p")) %>%
  papaja::apa_table(caption = "Results for Hypothesis 1",note="Hello world this is a table note",
                    col_spanners = list(`Confidence Intervals` = c(3, 4)))
```


# Results

# Discussion


\newpage

# References


\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
